import type { NavItem, Feature, Testimonial, PricingPlan, BlogPost, FAQItem } from "@/types";

export const NAV_ITEMS: NavItem[] = [
  { label: "Features", href: "/features" },
  { label: "Pricing", href: "/pricing" },
  { label: "About", href: "/about" },
  { label: "Blog", href: "/blog" },
  { label: "Contact", href: "/contact" },
];

export const FEATURES: Feature[] = [
  {
    id: "1",
    title: "Verified Identity",
    description: "KYC-grade identity verification with digital trust scores and professional badges that build instant credibility.",
    icon: "ShieldCheck",
    color: "blue",
  },
  {
    id: "2",
    title: "AI Matchmaking",
    description: "Intelligent business matching engine connects you with the right partners, clients, and collaborators.",
    icon: "Sparkles",
    color: "emerald",
  },
  {
    id: "3",
    title: "Lead Generation",
    description: "Qualified B2B lead marketplace with RFQ management and automated lead qualification systems.",
    icon: "TrendingUp",
    color: "blue",
  },
  {
    id: "4",
    title: "Trust Score System",
    description: "Comprehensive reputation analytics combining reviews, endorsements, and project completion ratings.",
    icon: "Star",
    color: "emerald",
  },
  {
    id: "5",
    title: "Smart Networking",
    description: "Industry-based networking suggestions powered by AI to expand your professional circle strategically.",
    icon: "Network",
    color: "blue",
  },
  {
    id: "6",
    title: "Business Intelligence",
    description: "Real-time dashboards with network growth analytics, lead conversion tracking, and opportunity reports.",
    icon: "BarChart3",
    color: "emerald",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Sarah Mitchell",
    title: "Founder & CEO",
    company: "Apex Ventures",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=80&h=80&fit=crop&crop=face",
    content: "TruNet transformed how we source business partnerships. The verified profiles and AI matchmaking helped us close 3 enterprise deals in the first month. The trust score system is a game-changer.",
    rating: 5,
    trustScore: 94,
  },
  {
    id: "2",
    name: "James Okonkwo",
    title: "Head of Business Development",
    company: "TechScale Global",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face",
    content: "The lead generation engine on TruNet is unlike anything I have used before. Qualified leads, verified businesses, and transparent reputation scores — it saves hours of due diligence.",
    rating: 5,
    trustScore: 91,
  },
  {
    id: "3",
    name: "Priya Sharma",
    title: "Senior Recruiter",
    company: "HireForce Pro",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face",
    content: "Finding verified talent used to take weeks. With TruNet's talent discovery and skill verification, we now onboard qualified candidates 60% faster. Absolute must-have for any recruiter.",
    rating: 5,
    trustScore: 88,
  },
  {
    id: "4",
    name: "Marcus Chen",
    title: "Independent Consultant",
    company: "Chen Strategy Group",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face",
    content: "As a freelancer, my trust score on TruNet has become my most valuable professional asset. Clients see my verified work history and reviews before even contacting me.",
    rating: 5,
    trustScore: 96,
  },
  {
    id: "5",
    name: "Adeola Williams",
    title: "Investment Partner",
    company: "Frontier Capital",
    avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=80&h=80&fit=crop&crop=face",
    content: "TruNet gives investors unprecedented visibility into startup founders and their track records. The verification system cuts through noise and surfaces genuine opportunities.",
    rating: 5,
    trustScore: 92,
  },
  {
    id: "6",
    name: "David Park",
    title: "Co-founder",
    company: "BuildFast Labs",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face",
    content: "We found our lead engineer, two anchor clients, and a distribution partner all through TruNet within 90 days. The platform's AI recommendations are eerily accurate.",
    rating: 5,
    trustScore: 89,
  },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "starter",
    name: "Starter",
    description: "Perfect for freelancers and independent professionals building their reputation.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    features: [
      "Verified professional profile",
      "Up to 50 network connections",
      "Basic trust score",
      "3 lead inquiries per month",
      "Community forum access",
      "Digital business card",
    ],
    highlighted: false,
  },
  {
    id: "professional",
    name: "Professional",
    description: "For growing professionals and small teams that need serious networking power.",
    monthlyPrice: 29,
    yearlyPrice: 23,
    features: [
      "Everything in Starter",
      "Unlimited connections",
      "Advanced trust score + KYC",
      "50 leads per month",
      "AI matchmaking engine",
      "Priority profile placement",
      "Analytics dashboard",
      "Message encryption",
    ],
    highlighted: true,
    badge: "Most Popular",
  },
  {
    id: "business",
    name: "Business",
    description: "Enterprise-grade tools for businesses, agencies, and high-volume teams.",
    monthlyPrice: 89,
    yearlyPrice: 71,
    features: [
      "Everything in Professional",
      "Unlimited leads",
      "Business verification badge",
      "Lead marketplace access",
      "Team management (5 seats)",
      "CRM integration",
      "Custom analytics reports",
      "API access",
      "Dedicated account manager",
    ],
    highlighted: false,
    badge: "Best Value",
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "1",
    title: "How Trust Scores Are Reshaping B2B Networking in 2026",
    excerpt: "The era of unverified business connections is ending. We explore how AI-powered trust scores are creating a new standard for professional credibility.",
    category: "Trust & Verification",
    author: "TruNet Editorial",
    authorAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=40&h=40&fit=crop&crop=face",
    date: "Jun 5, 2026",
    readTime: 6,
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=600&h=360&fit=crop",
    slug: "trust-scores-b2b-networking-2026",
  },
  {
    id: "2",
    title: "AI Matchmaking: The Future of Business Partnerships",
    excerpt: "Discover how TruNet's AI engine analyzes 200+ data points to surface business partnerships with 89% higher conversion rates than traditional networking.",
    category: "AI & Technology",
    author: "TruNet Editorial",
    authorAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=40&h=40&fit=crop&crop=face",
    date: "May 28, 2026",
    readTime: 8,
    image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&h=360&fit=crop",
    slug: "ai-matchmaking-business-partnerships",
  },
  {
    id: "3",
    title: "Building a 90-Day Reputation Strategy on TruNet",
    excerpt: "A practical playbook for professionals and businesses who want to build a high-trust reputation that generates inbound leads and partnership opportunities.",
    category: "Strategy",
    author: "TruNet Editorial",
    authorAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=40&h=40&fit=crop&crop=face",
    date: "May 15, 2026",
    readTime: 10,
    image: "https://images.unsplash.com/photo-1553484771-371a605b060b?w=600&h=360&fit=crop",
    slug: "90-day-reputation-strategy-trunet",
  },
  {
    id: "4",
    title: "The Verified Freelancer Advantage: Data & Insights",
    excerpt: "Our analysis of 50,000 verified freelancer profiles shows verified professionals earn 2.3x more and close projects 40% faster than unverified peers.",
    category: "Freelance",
    author: "TruNet Research",
    authorAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=40&h=40&fit=crop&crop=face",
    date: "May 8, 2026",
    readTime: 7,
    image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&h=360&fit=crop",
    slug: "verified-freelancer-advantage-data",
  },
];

export const FAQ_ITEMS: FAQItem[] = [
  {
    id: "1",
    question: "What is TruNet and who is it for?",
    answer: "TruNet is an AI-powered professional networking and business trust platform designed for professionals, freelancers, businesses, startups, recruiters, service providers, and enterprises. It focuses on building authentic connections, verified profiles, and trust-driven business opportunities.",
    category: "General",
  },
  {
    id: "2",
    question: "How does the Trust Score work?",
    answer: "Your Trust Score is calculated using a proprietary algorithm that factors in identity verification status, KYC completion, work history, peer endorsements, client reviews, project completion rates, response time, and time on platform. Scores range from 0-100 and are updated in real-time as you build your reputation.",
    category: "Trust & Verification",
  },
  {
    id: "3",
    question: "What is KYC verification and why do I need it?",
    answer: "KYC (Know Your Customer) verification confirms your real-world identity using government-issued ID and optional business documents. KYC-verified users receive a prominent verification badge, unlock higher trust scores, gain access to premium features, and are significantly more trusted by other users and businesses on the platform.",
    category: "Trust & Verification",
  },
  {
    id: "4",
    question: "How does AI matchmaking work?",
    answer: "TruNet's AI engine analyzes over 200 data points including your industry, skills, past collaborations, trust score, stated goals, network activity, and business needs to recommend high-quality matches for partnerships, clients, vendors, talent, and investors. The algorithm improves the more you use the platform.",
    category: "AI Features",
  },
  {
    id: "5",
    question: "Can I use TruNet to find clients as a freelancer?",
    answer: "Absolutely. TruNet has a dedicated Freelance & Service Marketplace where you can create a portfolio, publish service catalogs, respond to RFQs, submit proposals, manage contracts with milestone tracking, and build your reputation through verified client reviews.",
    category: "Freelance",
  },
  {
    id: "6",
    question: "How is TruNet different from LinkedIn?",
    answer: "Unlike LinkedIn which focuses on passive networking and job postings, TruNet is built around verified trust, active business transactions, lead generation, and AI-driven opportunity discovery. Every user has a verifiable Trust Score, KYC verification is available, and the platform actively facilitates business deals — not just connections.",
    category: "General",
  },
  {
    id: "7",
    question: "Is my data secure on TruNet?",
    answer: "Yes. TruNet uses enterprise-grade encryption for all data at rest and in transit. We are SOC 2 Type II compliant, GDPR-ready, and your personal verification documents are processed by a certified KYC provider and never stored on our servers after verification is complete.",
    category: "Security",
  },
  {
    id: "8",
    question: "Can I upgrade or downgrade my plan at any time?",
    answer: "Yes, you can change your plan at any time from your account settings. When upgrading, you get immediate access to new features and are charged a prorated amount. When downgrading, the change takes effect at the start of your next billing cycle.",
    category: "Billing",
  },
];

export const STATS = [
  { value: "240K+", label: "Verified Professionals", suffix: "" },
  { value: "18K+", label: "Business Partnerships Formed", suffix: "" },
  { value: "94%", label: "Lead Conversion Rate", suffix: "" },
  { value: "$2.4B+", label: "Business Value Facilitated", suffix: "" },
];

export const WORKFLOW_STEPS = [
  {
    step: "01",
    title: "Create & Verify Your Profile",
    description: "Register in minutes, complete identity verification, and receive your Trust Score badge that signals credibility to everyone on the platform.",
    icon: "UserCheck",
  },
  {
    step: "02",
    title: "AI Discovers Your Opportunities",
    description: "Our matchmaking engine analyzes your profile, goals, and network to surface relevant connections, leads, partnerships, and job opportunities.",
    icon: "Sparkles",
  },
  {
    step: "03",
    title: "Connect & Collaborate",
    description: "Engage with verified professionals and businesses through encrypted messaging, digital business cards, and collaboration rooms.",
    icon: "Handshake",
  },
  {
    step: "04",
    title: "Grow Your Trust & Revenue",
    description: "Complete deals, earn verified reviews, and watch your Trust Score and reputation compound into a powerful business development asset.",
    icon: "TrendingUp",
  },
];
